FROM ruby:3.0.3-slim-buster
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs cron

RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler:2.3.9
COPY . /myapp

RUN bundle install
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0"]
# ENTRYPOINT rails db:create && rails db:migrate && rails db:seed

